name: NPM Audit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:

      - name: Install dependencies
        run: npm install

      - name: Run npm audit
        run: npm audit
